version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:${HOME}/prePassItOn/"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install -r requirements.txt
      - run: pytest --version
      - run: python code/main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:${HOME}/prePassItOn/"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install -r requirements.txt
      - run: pytest --version
      - run: python test/main-test.py
      - run: pytest -vvv test/test_main.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build